CREATE TABLE countries
(
    iso  CHAR(2) PRIMARY KEY,
    name VARCHAR(50) UNIQUE
);

CREATE TABLE users
(
    id       SERIAL PRIMARY KEY,
    email    VARCHAR(100) NOT NULL UNIQUE,
    username VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    enabled  BOOLEAN      NOT NULL
);

CREATE TABLE cities
(
    id           SERIAL PRIMARY KEY,
    name         VARCHAR(100),
    country_code CHAR(2) REFERENCES countries (iso),
    latitude     NUMERIC(5),
    longitude    NUMERIC(5)
);

CREATE TABLE authorities
(
    username  VARCHAR(100) NOT NULL,
    authority VARCHAR(100) NOT NULL,
    CONSTRAINT fk_authorities_users FOREIGN KEY (username) REFERENCES users (email)
);

CREATE UNIQUE INDEX ix_auth_users ON authorities (username, authority);

CREATE TABLE city_visit
(
    user_id INTEGER REFERENCES users (id),
    city_id INTEGER REFERENCES cities (id),
    PRIMARY KEY (user_id, city_id)
);

CREATE TABLE country_visit
(
    user_id      INTEGER REFERENCES users (id),
    country_code CHAR(2) REFERENCES countries (iso),
    PRIMARY KEY (user_id, country_code)
);

INSERT INTO countries (iso, name)
VALUES ('AB', 'Abkhazia'),
       ('AD', 'Andorra'),
       ('AE', 'United Arab Emirates'),
       ('AF', 'Afghanistan'),
       ('AG', 'Antigua and Barbuda'),
       ('AI', 'Anguilla'),
       ('AL', 'Albania'),
       ('AM', 'Armenia'),
       ('AO', 'Angola'),
       ('AR', 'Argentina'),
       ('AS', 'American Samoa'),
       ('AT', 'Austria'),
       ('AU', 'Australia'),
       ('AZ', 'Azerbaijan'),
       ('BA', 'Bosnia and Herzegovina'),
       ('BB', 'Barbados'),
       ('BD', 'Bangladesh'),
       ('BE', 'Belgium'),
       ('BF', 'Burkina Faso'),
       ('BG', 'Bulgaria'),
       ('BH', 'Bahrain'),
       ('BI', 'Burundi'),
       ('BJ', 'Benin'),
       ('BL', 'Saint Barthelemy'),
       ('BM', 'Bermuda'),
       ('BN', 'Brunei Darussalam'),
       ('BO', 'Bolivia'),
       ('BQ', 'Bonaire, Sint Eustatius and Saba'),
       ('BR', 'Brazil'),
       ('BS', 'Bahamas'),
       ('BT', 'Bhutan'),
       ('BW', 'Botswana'),
       ('BY', 'Belarus'),
       ('BZ', 'Belize'),
       ('CA', 'Canada'),
       ('CD', 'Democratic Republic of the Congo'),
       ('CF', 'Central African Republic'),
       ('CG', 'Congo'),
       ('CH', 'Switzerland'),
       ('CI', 'Cote D Ivoire'),
       ('CL', 'Chile'),
       ('CM', 'Cameroon'),
       ('CN', 'China'),
       ('CO', 'Colombia'),
       ('CR', 'Costa Rica'),
       ('CU', 'Cuba'),
       ('CV', 'Cape Verde'),
       ('CY', 'Cyprus'),
       ('CZ', 'Czech Republic'),
       ('DE', 'Germany'),
       ('DJ', 'Djibouti'),
       ('DK', 'Denmark'),
       ('DM', 'Dominica'),
       ('DO', 'Dominican Republic'),
       ('DZ', 'Algeria'),
       ('EC', 'Ecuador'),
       ('EE', 'Estonia'),
       ('EG', 'Egypt'),
       ('EH', 'Western Sahara'),
       ('ER', 'Eritrea'),
       ('ES', 'Spain'),
       ('ET', 'Ethiopia'),
       ('FI', 'Finland'),
       ('FJ', 'Fiji'),
       ('FK', 'Falkland Islands (Malvinas)'),
       ('FM', 'Federated States of Micronesia'),
       ('FO', 'Faroe Islands'),
       ('FR', 'France'),
       ('GA', 'Gabon'),
       ('GB', 'United Kingdom'),
       ('GD', 'Grenada'),
       ('GE', 'Georgia'),
       ('GF', 'French Guiana'),
       ('GG', 'Guernsey'),
       ('GH', 'Ghana'),
       ('GI', 'Gibraltar'),
       ('GL', 'Greenland'),
       ('GM', 'Gambia'),
       ('GN', 'Guinea'),
       ('GP', 'Guadeloupe'),
       ('GQ', 'Equatorial Guinea'),
       ('GR', 'Greece'),
       ('GT', 'Guatemala'),
       ('GU', 'Guam'),
       ('GW', 'Guinea-Bissau'),
       ('GY', 'Guyana'),
       ('HK', 'Hong Kong'),
       ('HN', 'Honduras'),
       ('HR', 'Croatia'),
       ('HT', 'Haiti'),
       ('HU', 'Hungary'),
       ('ID', 'Indonesia'),
       ('IE', 'Ireland'),
       ('IL', 'Israel'),
       ('IM', 'Isle of Man'),
       ('IN', 'India'),
       ('IO', 'British Indian Ocean Territory'),
       ('IQ', 'Iraq'),
       ('IR', 'Iran'),
       ('IS', 'Iceland'),
       ('IT', 'Italy'),
       ('JE', 'Jersey'),
       ('JM', 'Jamaica'),
       ('JO', 'Jordan'),
       ('JP', 'Japan'),
       ('KE', 'Kenya'),
       ('KG', 'Kyrgyzstan'),
       ('KH', 'Cambodia'),
       ('KI', 'Kiribati'),
       ('KM', 'Comoros'),
       ('KN', 'Saint Kitts and Nevis'),
       ('KP', 'North Korea'),
       ('KR', 'South Korea'),
       ('KW', 'Kuwait'),
       ('KY', 'Cayman Islands'),
       ('KZ', 'Kazakhstan'),
       ('LA', 'Laos'),
       ('LB', 'Lebanon'),
       ('LC', 'Saint Lucia'),
       ('LI', 'Liechtenstein'),
       ('LK', 'Sri Lanka'),
       ('LR', 'Liberia'),
       ('LS', 'Lesotho'),
       ('LT', 'Lithuania'),
       ('LU', 'Luxembourg'),
       ('LV', 'Latvia'),
       ('LY', 'Libya'),
       ('MA', 'Morocco'),
       ('MD', 'Moldova'),
       ('ME', 'Montenegro'),
       ('MG', 'Madagascar'),
       ('MK', 'North Macedonia'),
       ('ML', 'Mali'),
       ('MM', 'Myanmar'),
       ('MN', 'Mongolia'),
       ('MP', 'Northern Mariana Islands'),
       ('MQ', 'Martinique'),
       ('MR', 'Mauritania'),
       ('MS', 'Montserrat'),
       ('MT', 'Malta'),
       ('MU', 'Mauritius'),
       ('MV', 'Maldives'),
       ('MW', 'Malawi'),
       ('MX', 'Mexico'),
       ('MY', 'Malaysia'),
       ('MZ', 'Mozambique'),
       ('NA', 'Namibia'),
       ('NC', 'New Caledonia'),
       ('NE', 'Niger'),
       ('NG', 'Nigeria'),
       ('NI', 'Nicaragua'),
       ('NL', 'Netherlands'),
       ('NO', 'Norway'),
       ('NP', 'Nepal'),
       ('NR', 'Nauru'),
       ('NZ', 'New Zealand'),
       ('OM', 'Oman'),
       ('OS', 'South Ossetia'),
       ('PA', 'Panama'),
       ('PE', 'Peru'),
       ('PF', 'French Polynesia'),
       ('PG', 'Papua New Guinea'),
       ('PH', 'Philippines'),
       ('PK', 'Pakistan'),
       ('PL', 'Poland'),
       ('PM', 'Saint Pierre and Miquelon'),
       ('PN', 'Pitcairn'),
       ('PR', 'Puerto Rico'),
       ('PS', 'Palestinian Territory'),
       ('PT', 'Portugal'),
       ('PW', 'Palau'),
       ('PY', 'Paraguay'),
       ('QA', 'Qatar'),
       ('RE', 'Reunion'),
       ('RO', 'Romania'),
       ('RS', 'Serbia'),
       ('RU', 'Russian Federation'),
       ('RW', 'Rwanda'),
       ('SA', 'Saudi Arabia'),
       ('SB', 'Solomon Islands'),
       ('SC', 'Seychelles'),
       ('SD', 'Sudan'),
       ('SE', 'Sweden'),
       ('SG', 'Singapore'),
       ('SH', 'Saint Helena'),
       ('SI', 'Slovenia'),
       ('SK', 'Slovakia'),
       ('SL', 'Sierra Leone'),
       ('SM', 'San Marino'),
       ('SN', 'Senegal'),
       ('SO', 'Somalia'),
       ('SR', ' Suriname'),
       ('SS', 'South Sudan'),
       ('ST', 'Sao Tome and Principe'),
       ('SV', 'El Salvador'),
       ('SY', 'Syrian Arab Republic'),
       ('SZ', 'Swaziland'),
       ('TC', 'Turks and Caicos Islands'),
       ('TD', 'Chad'),
       ('TF', 'French Southern Territories'),
       ('TG', 'Togo'),
       ('TH', 'Thailand'),
       ('TJ', 'Tajikistan'),
       ('TK', 'Tokelau'),
       ('TL', 'Timor-Leste'),
       ('TM', 'Turkmenistan'),
       ('TN', 'Tunisia'),
       ('TO', 'Tonga'),
       ('TR', 'Turkey'),
       ('TT', 'Trinidad and Tobago'),
       ('TV', 'Tuvalu'),
       ('TZ', 'Tanzania'),
       ('UA', 'Ukraine'),
       ('UG', 'Uganda'),
       ('UM', 'United States Minor Outlying Islands'),
       ('US', 'United States'),
       ('UY', 'Uruguay'),
       ('UZ', 'Uzbekistan'),
       ('VC', 'Saint Vincent and the Grenadines'),
       ('VE', 'Venezuela'),
       ('VG', 'Virgin Islands, British'),
       ('VI', 'Virgin Islands, US.'),
       ('VN', 'Viet Nam'),
       ('VU', 'Vanuatu'),
       ('WF', 'Wallis and Futuna'),
       ('WS', 'Samoa'),
       ('YE', 'Yemen'),
       ('YT', 'Mayotte'),
       ('ZA', 'South Africa'),
       ('ZM', 'Zambia'),
       ('ZW', 'Zimbabwe');
